#!/bin/bash
 
ACTION=none
DATABASE=default.db


usage() {
    cat <<EOL
Usage: filechecker <init|scan> [OPTIONS] <source_dir>
Options:
    --dbname <database>: Database file.
EOL
}

if [[ $# -lt 2 ]]; then         # checking number of arguments
    usage
    exit 1
fi

case $1 in                      # checking what action should be done
    "init")
        ACTION=init
        shift 1
        ;;
    "scan")
        ACTION=scan
        shift 1
        ;;
    *)
        echo "ERROR: Undefined ACTION."
        exit 1
        ;;
esac

while true; do                  # checking if the database is given or not
    case $1 in                  # database is for writing when action is init
        "--dbname")             # database is for comparing when action is scan
            DATABASE=$2
            shift 2
            ;;
        *)
            break
            ;;
    esac
done

case $ACTION in                 # the main action will be done in this block
    "init")
        if [[ $# -ne 1 ]]; then
            usage
            exit 1
        fi

        if [[ ! -d $1 ]]; then
            echo "ERROR: $1 should be a directory."
            exit 1
        fi
        # creating history from source directory
        FILES=($(tree -iRfan --noreport $1 | grep -Ev "\->|error openning dir"))
        if [[ ! -e $DATABASE ]]; then
            for FILE in ${FILES[@]}; do
                CHECKSUM=($(md5sum $FILE 2> /dev/null))
                if [[ $? -eq 0 ]]; then
                    echo "${CHECKSUM[0]} ${CHECKSUM[1]}" >> $DATABASE
                fi
            done
        else
            rm $DATABASE
            for FILE in ${FILES[@]}; do
                CHECKSUM=($(md5sum $FILE 2> /dev/null))
                if [[ $? -eq 0 ]]; then
                    echo "${CHECKSUM[0]} ${CHECKSUM[1]}" >> $DATABASE
                fi
            done        
        fi  
        ;;
    "scan")
        if [[ $# -ne 1 ]]; then
            usage
            exit 1
        fi

        if [[ ! -d $1 ]]; then
            echo "ERROR: $1 should be a directory."
            exit 1
        fi
        # creating history from source directory
        FILES=($(tree -iRfan --noreport $1 | grep -Ev "\->|error openning dir"))
        touch temp.db
        for FILE in ${FILES[@]}; do
            CHECKSUM=($(md5sum $FILE 2> /dev/null))
            if [[ $? -eq 0 ]]; then
                echo "${CHECKSUM[0]} ${CHECKSUM[1]}" >> temp.db
            fi        
        done

        # comparing the created history and database file
        if cmp -s "./temp.db" "./$DATABASE" ; then
            echo "Nothing has been changed."
        else
            echo -e "There is some changes:\n"
            echo -e "\t\t\told database\t\t\t\t\t\t\tnew database"
            diff --suppress-common-lines -y ./temp.db ./$DATABASE
            echo -e ""
        fi
        rm temp.db
        ;;
    *)
        echo "ERROR: Undefined Action."
        exit 1
        ;;
esac