#!/bin/bash

function_file_print_unccommented_lines() {
    Usage() {
        cat <<EOL
Usage: $0 <file>
EOL
    }

    if [[ $# -ne 1 ]]; then
        Usage
        exit 1
    fi

    if [[ ! -e $1 ]]; then
        echo "ERROR: $1 does not exitst"
        Usage
        exit 1
    fi

    if [[ ! -f $1 ]]; then
        echo "ERROR: $1 should be a file."
        Usage
        exit 1
    fi
    
    while true; do
        grep -v '^*#' $1
        if [[ $? -eq 0 ]]; then
            exit 0
        fi
    done
}
