#!/bin/bash

function_get_password() {

	read -s -p "Enter the password:" password
	echo ""
	read -s -p "Enter the password again:" confirmation
	echo ""

	if [[ '$password' == '$confirmation' ]]; then
		return $password
		exit 0
	else
		echo "The password and confirmation doesn't match."
		exit 1
	fi

}
